if: (type = push AND branch = master) OR type = pull_request
sudo: false
language: node_js
services:
  - docker
before_install:
  - if [ $TEST_SUITE = "integration" ] ; then
      docker pull junderw/btcpay-client-test-server &&
      docker run -d -p 127.0.0.1:49392:49392 -p 127.0.0.1:8080:8080 -p 127.0.0.1:18271:18271 junderw/btcpay-client-test-server &&
      docker ps -a &&
      sleep 10;
    fi
node_js:
  - "10"
  - "13"
  - "lts/*"
matrix:
  include:
    - node_js: "lts/*"
      env: TEST_SUITE=gitdiff:ci
    - node_js: "lts/*"
      env: TEST_SUITE=integration
    - node_js: "lts/*"
      env: TEST_SUITE=coverage
env:
  - TEST_SUITE=test
script: npm run $TEST_SUITE
